In [4]:
# Daniel Bandala @ mar 2022
import numpy as np
from sklearn import metrics
from keras.models import Sequential
from keras.layers import Dense,Input

# AND Gate perceptron

This script build a multilayer perceptron with 1 hidden layer trained to model a AND logic gate.

In [19]:
# AND gate data
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])

In [20]:
model = Sequential()
model.add(Dense(1,input_dim=2,activation='relu'))

In [21]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['acc'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


<img src='https://www.allaboutcircuits.com/uploads/articles/how-to-perform-classification-using-a-neural-network-a-simple-perceptron-example_rk_aac_image1.jpg'>

In [22]:
# initialize model
model.set_weights([np.array([[0.5],[0.5]]),np.array([-0.5])])

In [27]:
# train model
model.fit(X,y,epochs=400,verbose=False)
print("Network weights")
model.get_weights()

Network weights


[array([[0.9244937],
        [0.9244937]], dtype=float32),
 array([-0.8935135], dtype=float32)]

In [28]:
y_pred = model.predict(X)
for i in range(len(y_pred)):
    print("Input: ",X[i]," | Output: ",y[i]," | Estimated output: ",y_pred[i])

Input:  [0 0]  | Output:  0  | Estimated output:  [0.]
Input:  [0 1]  | Output:  0  | Estimated output:  [0.03098017]
Input:  [1 0]  | Output:  0  | Estimated output:  [0.03098017]
Input:  [1 1]  | Output:  1  | Estimated output:  [0.95547384]


## Using one hidden layer and two outputs

In [37]:
model = Sequential()
model.add(Dense(3,input_dim=2,activation='softmax'))
model.add(Dense(1,activation='relu'))

In [38]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['acc'])
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 3)                 9         
                                                                 
 dense_10 (Dense)            (None, 1)                 4         
                                                                 
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


<img src='https://www.allaboutcircuits.com/uploads/articles/an-introduction-to-training-theory-for-neural-networks_rk_aac_image2.jpg'>

In [39]:
# train model
model.fit(X,y,epochs=1200,verbose=False)
print("Network weights")
model.get_weights()

Network weights


[array([[-0.82816416, -0.33834943, -1.7722634 ],
        [-0.06555569,  1.3727115 ,  0.06053998]], dtype=float32),
 array([-0.43876132, -0.43739828,  0.8926503 ], dtype=float32),
 array([[-0.47531417],
        [ 1.8982205 ],
        [-1.6133776 ]], dtype=float32),
 array([-0.05332297], dtype=float32)]

In [40]:
y_pred = model.predict(X)
for i in range(len(y_pred)):
    print("Input: ",X[i]," | Output: ",y[i]," | Estimated output: ",y_pred[i])

Input:  [0 0]  | Output:  0  | Estimated output:  [0.]
Input:  [0 1]  | Output:  0  | Estimated output:  [0.01012767]
Input:  [1 0]  | Output:  0  | Estimated output:  [0.00761831]
Input:  [1 1]  | Output:  1  | Estimated output:  [0.9825327]
